### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by 3nityGitHub** [Feliverse/Felipe-Portfolio#3]
@Feliverse In order to keep your stylesheet less repetitive and DRY, consider creating a class for the display: flex; property since it will be coming in handy all throughout this project.
example

.flex {

  display: flex;

}

You can truly reuse this class in your HTML tags without ever declaring display: flex; anymore

**Comment by Feliverse** [comment]
Hey @3nityGitHub 
thank you
